version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_NUM_PARTITIONS: 8
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://kafka:29092,PLAINTEXT://kafka:9092'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "kubertron.weather.inbound:1:1:compact"

  kafka-rest:
    image: 'confluentinc/cp-kafka-rest:latest'
    hostname: kafka-rest
    ports:
      - '8082:8082'
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_REST_CONSUMER_INSTANCE_TIMEOUT_MS: 300000
      KAFKA_REST_CONSUMER_REQUEST_TIMEOUT_MS: 30000
      KAFKA_REST_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka:9092'

  kafka-topics-ui:
    image: 'landoop/kafka-topics-ui:0.9.4'
    hostname: kafka-topics-ui
    ports:
      - 8000:8000
    depends_on:
      - zookeeper
      - kafka
      - kafka-rest
    environment:
      KAFKA_REST_PROXY_URL: 'http://kafka-rest:8082'
      RECORD_POLL_TIMEOUT: 5000
      PROXY: 'true'
      PROXY_SKIP_VERIFY: 'true'
      MAX_BYTES: 100000
      DEBUG_LOGS_ENABLED: 'true'
